// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-IW5xCukeS5-6WkEBiSmz-uJzGnBUCmI',
    appId: '1:365920485285:web:db7f85ccaa53eda2d6724c',
    messagingSenderId: '365920485285',
    projectId: 'notepad-bd83a',
    authDomain: 'notepad-bd83a.firebaseapp.com',
    storageBucket: 'notepad-bd83a.firebasestorage.app',
    measurementId: 'G-LSEPS5KSL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-yWIivVJl1-2RUAdLBrZFs2nr-uJ33dw',
    appId: '1:365920485285:android:6169afa22b360c21d6724c',
    messagingSenderId: '365920485285',
    projectId: 'notepad-bd83a',
    storageBucket: 'notepad-bd83a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8oH3bHA1P4ILB4J2B77VfHXsZCnD2hEE',
    appId: '1:365920485285:ios:e7edadab2d9c92f9d6724c',
    messagingSenderId: '365920485285',
    projectId: 'notepad-bd83a',
    storageBucket: 'notepad-bd83a.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8oH3bHA1P4ILB4J2B77VfHXsZCnD2hEE',
    appId: '1:365920485285:ios:e7edadab2d9c92f9d6724c',
    messagingSenderId: '365920485285',
    projectId: 'notepad-bd83a',
    storageBucket: 'notepad-bd83a.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-IW5xCukeS5-6WkEBiSmz-uJzGnBUCmI',
    appId: '1:365920485285:web:7825cfe819a71ce6d6724c',
    messagingSenderId: '365920485285',
    projectId: 'notepad-bd83a',
    authDomain: 'notepad-bd83a.firebaseapp.com',
    storageBucket: 'notepad-bd83a.firebasestorage.app',
    measurementId: 'G-C55H8GZE6K',
  );
}
